name: EtyNote
options:
  createIntermediateGroups: true
targets:
  EtyNote:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - App
      - Core
      - Features
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.backwell88.EtyNote
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: 5.9
        CODE_SIGNING_ALLOWED: YES

